version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: logistics-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: i1112006s
      POSTGRES_DB: logistics
    ports:
      - "5432:5432"
    volumes:
      - logistics_pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: logistics-redis
    ports:
      - "6379:6379"
    volumes:
      - logistics_redisdata:/data
    restart: always

volumes:
  logistics_pgdata:
  logistics_redisdata: